development:
    adapter: postgresql
    encoding: unicode
    database: something
    host: localhost
    username: postgres
    password: '123'
    port: 5434
    pool: 5


production:
    adapter: postgresql
    encoding: unicode
    database: something
    host: localhost
    username: postgres
    password: '123'
    port: 5434
    pool: 5


test:
    adapter: postgresql
    encoding: unicode
    database: something_test
    host: localhost
    username: postgres
    password: '123'
    port: 5434
    pool: 5